<?php

/* Originally from Icinga Web 2 Elasticsearch Module (c) 2017 Icinga Development Team | GPLv2+ */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\__Modulename__\Controllers;

use Icinga\Web\Controller;

use Icinga\Module\__Modulename__\Forms\__Configname__Form;
use Icinga\Module\__Modulename__\__Configname__IniRepository;

class __Configname__Controller extends Controller
{
    /**
     * Set the title tab
     *
     * @param   string  $label
     */
    public function setTitle($label)
    {
        $this->getTabs()->add(uniqid(), [
            'active'    => true,
            'label'     => $label,
            'url'       => $this->getRequest()->getUrl()
        ]);
    }


    public function init()
    {
        $this->assertPermission('__modulename__/__configname__/config');
    }

    public function indexAction()
    {
        $this->setTitle($this->translate('__ConfignamePL__'));
        $this->view->configs = (new __Configname__IniRepository())->select(['name']);

        $this->_helper->viewRenderer->setRender('__configname__/__configview__', null, true);
    }

    public function newAction()
    {
        $form = new __Configname__Form([
            'mode'  => __Configname__Form::MODE_INSERT
        ]);

        $form->handleRequest();

        $this->setTitle($this->translate('New __Configname__'));

        $this->view->form = $form;

        $this->_helper->viewRenderer->setRender('form', null, true);
    }

    public function updateAction()
    {
        $id = $this->params->getRequired('id');

        $form = new __Configname__Form([
            'mode'          => __Configname__Form::MODE_UPDATE,
            'identifier'    => $id
        ]);

        $form->handleRequest();


        $this->setTitle($this->translate('Update __Configname__'));

        $this->view->form = $form;

        $this->_helper->viewRenderer->setRender('form', null, true);
    }

    public function deleteAction()
    {
        $id = $this->params->getRequired('id');

        $form = new __Configname__Form([
            'mode'          => __Configname__Form::MODE_DELETE,
            'identifier'    => $id
        ]);

        $form->handleRequest();

        $this->setTitle($this->translate('Remove __Configname__'));

        $this->view->form = $form;

        $this->_helper->viewRenderer->setRender('form', null, true);
    }
}
