<?php

/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\__Modulename__\Controllers;

use ipl\Web\Url;
use ipl\Html\Html;
use ipl\Web\Compat\CompatController;

class CompatIndexController extends CompatController
{
    public function indexAction()
    {
        $this->addTitleTab(t('__Modulename__ Compat'));
        $this->addContent(Html::tag('h1', 'Hello there!'));
        $file = __FILE__;
        $this->addContent(Html::tag('p', "This is your IndexController located at {$file}"));
    }


}
