<?php

/* originally from Icinga Web 2 X.509 Module | (c) 2018 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\__Modulename__\Controllers;

use HttpException;
use Icinga\Application\Config;
use Icinga\Module\Statuspage\Common\Database;
use Icinga\Module\Statuspage\FileHelper;
use Icinga\Module\Statuspage\Forms\BackendConfigForm;
use Icinga\Module\Statuspage\SqliteFileHelper;
use Icinga\Module\Statuspage\SqliteFilesTable;
use Icinga\Web\Notification;
use ipl\Html\Html;
use ipl\Web\Compat\CompatController;
use ipl\Web\Widget\ButtonLink;
use SQLite3;

class ConfigController extends CompatController
{
    protected $path;
    public function init()
    {
        $this->assertPermission('config/__modulename__');
        parent::init();
    }

    public function backendAction()
    {
        $form = (new BackendConfigForm())
            ->setIniConfig(Config::module('__modulename__'));

        $form->handleRequest();

        $this->view->tabs = $this->Module()->getConfigTabs()->activate('backend');
        $this->view->form = $form;
    }
}
