<div class="controls">
    <?= /** @var \Icinga\Web\Widget\Tabs $tabs */ $tabs ?>
</div>
<div class="content">
    <div class="actions">
        <?= $this->qlink(
            $this->translate('Create a New __Configname__') ,
            '__modulename__/__configname__/new',
            null,
            [
                'class'             => 'button-link',
                'data-base-target'  => '_next',
                'icon'              => 'plus',
                'title'             => $this->translate('Create a New Job')
            ]
        ) ?>
    </div>
<?php /** @var \Icinga\Repository\RepositoryQuery $configs */ if (! $configs->hasResult()): ?>
    <p><?= $this->escape($this->translate('No __Configname__ configured yet.')) ?></p>
<?php else: ?>
    <table class="common-table table-row-selectable" data-base-target="_next">
        <thead>
            <tr>
                <th><?= $this->escape($this->translate('Name')) ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($configs as $config): ?>
            <tr>
                <td><?= $this->qlink($config->name, '__modulename__/__configname__/update', ['id' => $config->name]) ?></td>
                <td class="icon-col"><?= $this->qlink(
                        null,
                        '__modulename__/__configname__/delete',
                        array('id' => $config->name),
                        array(
                            'class' => 'action-link',
                            'icon'  => 'cancel',
                            'title' => $this->translate('Remove this __Configname__')
                        )
                    ) ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>
</div>
